CREATE SEQUENCE Supplier_Details_Seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Customer_Details_Seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Transporter_Details_Seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Products_Seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Storage_Compartments_Seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Distribution_Compartments_Seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE StorageW_Region_Seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DistributionW_Region_Seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Allocation_Details_Seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Purchase_Order_seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Sales_Order_seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Transport_Order_seq MINVALUE 1 START WITH 1 INCREMENT BY 1;


